# Generated by Django 4.0.1 on 2022-02-13 15:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_comment_comm_name_alter_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
